name: Build Docker Image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/build-docker-image.yml
      - Dockerfile
  schedule:
    - cron: "15 3 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: egvimo/ansible:latest
